# -*- coding: utf-8 -*-
"""standarization solution (with Runnable).ipynb

Automatically generated by Colab.

"""

from abc import ABC, abstractmethod

class Runnable(ABC):

  @abstractmethod
  def invoke(input_data):
    pass

import random

class NakliLLM(Runnable):

  def __init__(self):
    print('LLM created')

  def invoke(self, prompt):
     response_list = [
        "Delhi is the capital of India",
        "IPL is a cricket league",
        "AI stands for Artifical Intelligent"
    ]


  def predict(self, prompt):

    response_list = [
        "Delhi is the capital of India",
        "IPL is a cricket league",
        "AI stands for Artifical Intelligent"
    ]

    return{'response': 'This method is deprected so do-not use it'}

class NakliPromptTemplate(Runnable):

  def __init__(self, template, input_variables):
    self.template = template
    self.input_variables = input_variables

  def invoke(self, input_dict):
    return self.template.format(**input_dict)

  def format(self, input_dict):
    return self.template.format(**input_dict) # insist of this return This method is deprected so do-not use it

class RunnableConnector(Runnable):

  def __init__(self, runnable_list):
   self.runnable_list = runnable_list

  def invoke(self, input_data):
    for runnable in self.runnable_list:
      input_data = runnable.invoke(input_data)
    return input_data

template = NakliPromptTemplate(
    template='Write a {length} poem about {topic}',
    input_variables=['length', 'topic']
)

llm = NakliLLM()

chain = RunnableConnector([template, llm])

chain.invoke({'length':'long','topic':'india'})

