
"""tools-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qS7oDBzQdsL9JGnt52vUt-MJw0znnYsc
"""


"""Built-in Tool - DuckDuckGo Search"""

from langchain_community.tools import DuckDuckGoSearchRun
from langchain_community.tools import ShellTool
from langchain_core.tools import tool
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field
from langchain_core.tools import BaseTool
from typing import Type
from langchain_core.tools import Tool


search_tool = DuckDuckGoSearchRun()

results = search_tool.invoke('ipl news')

print(results)

"""Built-in Tool - Shell Tool"""


shell_tool = ShellTool()

results = shell_tool.invoke('whoami')

print(results)

"""Custom Tools"""



# Step 1 - create a function
def multiply(a,b):
    """Multiply two numbers"""
    return a*b

# Step 2 - add type hints
def multiply(a: int, b: int) -> int:
    """Multiply two numbers"""
    return a*b

# Step 3 - add tool decorator
@tool
def multiply(a: int, b: int) -> int:
    """Multiply two numbers"""
    return a*b

results = multiply.invoke({"a":3, "b":5})

print(results)

print(multiply.name)
print(multiply.description)
print(multiply.args)

print(multiply.args_schema.model_json_schema())

"""Using StructuredTool and Pydantic"""



class MultiplyInput(BaseModel):
    a: int = Field(required=True, description="First number to add")
    b: int = Field(required=True, description="Second number to add")

def multiply_func(a: int, b: int) -> int:
    return a*b

multiply_tool = StructuredTool.from_function(
    func=multiply_func,
    name="multiply",
    description="Multiply two numbers",
    args_schema=MultiplyInput
)

result = multiply_tool.invoke({"a":3, "b":5})
print(result)
print(multiply_tool.name)
print(multiply_tool.description)
print(multiply_tool.args)

"""Using BaseTool

"""


# arg schema using pydantic
class MultiplyInput(BaseModel):
    a: int = Field(required=True, description="First number to add")
    b: int = Field(required=True, description="Second number to add")

class MultiplyTool(BaseTool):
    name: str = "multiply"
    description: str = "Multiply two numbers"

    args_schema: Type[BaseModel] = MultiplyInput

    def _run(self, a: int, b: int) -> int:
        return a*b

multiply_tool = MultiplyTool()

result = multiply_tool.invoke({"a":5, "b":7})
print(result)
print(multiply_tool.name)
print(multiply_tool.description)
print(multiply_tool.args)

"""Toolkits"""


# custom tools
@tool
def add(a: int, b: int) -> int:
    """Add two numbers"""
    return a+b

@tool
def multiply(a: int, b: int) -> int:
    """Multiply two numbers"""
    return a*b

@tool
def subtract(a: int, b: int) -> int:
    """Subtract two numbers"""
    return a-b

class MathToolkit:
    def get_tools(self):
        return[add,multiply,subtract]

toolkit = MathToolkit()
tools =  toolkit.get_tools()
for tool in tools:
    print(tool.name, "=>", tool.description)

