
"""tool-calling-in-langchain.ipynb

Automatically generated by Colab.

"""
import os
EXCHANGE_API_KEY = os.environ.get("EXCHANGE_API_KEY")

from langchain_groq import ChatGroq
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests
import json
from dotenv import load_dotenv
load_dotenv()

# tool create

@tool
def multiply(a: int, b: int) -> int:
        """Given 2 numbers a and b this tools returns their product"""
        return a * b

print(multiply.invoke({"a":3, "b":4}))

print(multiply.name)

print(multiply.description)

print(multiply.args)

# tool binding
llm = ChatGroq( model="openai/gpt-oss-120b", temperature=0.4)

llm_with_tool = llm.bind_tools([multiply])

print(llm_with_tool)

print(llm_with_tool.invoke('Hi how are you'))

query = HumanMessage('can you multiply 3 and 1000')

messages = [query]

print(messages)

result = llm_with_tool.invoke(messages)

messages.append(result)

print(messages)

print(result.tool_calls[0]['args'])

# Tool execution
tool_result = multiply.invoke(result.tool_calls[0])

messages.append(tool_result)

print(messages)

llm_with_tool.invoke(messages).content

# Currency Conversion - tool create
@tool
def get_conversion_factor(base_currency: str, target_currency: str) -> float:
  """
  This function fetches the currency factor between a given base currency and a target currency
  """

  url = f"https://v6.exchangerate-api.com/v6/{EXCHANGE_API_KEY}/pair/{base_currency}/{target_currency}"
  response = requests.get(url)
  return response.json()

@tool
def convert(base_currency_value: int, conversion_rate: float) -> float:
  """
  Given a currency rate this function calculates the target currency value from agiven base currency value
  """
  return base_currency_value * conversion_rate

get_conversion_factor.invoke({"base_currency":"USD", "target_currency":"INR"})

convert.invoke({"base_currency_value": 10, "conversion_rate": 95.4392})

# tool binding

llm = ChatGroq( model="openai/gpt-oss-120b", temperature=0.4)

llm_with_tool = llm.bind_tools([get_conversion_factor, convert])

messages = [HumanMessage('can you convert 10 USD to INR ,and based on that can you convert 10 usd into inr')]

print(messages)

ai_message = llm_with_tool.invoke(messages)

print(ai_message)

print(ai_message.tool_calls)


for tool_call in ai_message.tool_calls:
  # execute the 1st tool and get the value of conversion rate
  if tool_call['name'] == 'get_conversion_factor':
    tool_message1 = get_conversion_factor.invoke(tool_call)
    # fetch this conversion rate
    conversion_rate = json.loads(tool_message1.content)['conversion_rate']
    # append this tool message to messages list
    messages.append(tool_message1)
  # execute the 2nd tool using the conversion rate from tool 1
  if tool_call['name'] == 'convert':
    # fetch the current arg
    tool_call['args']['conversion_rate'] = conversion_rate
    tool_message2 = convert.invoke(tool_call)
    messages.append(tool_message2)

print(messages)

llm_with_tool.invoke(messages).content

